version: '3.8'

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5

  web:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword
      - Jwt__Key=3b479a30c265b956a965a63f40d825a54d1d0106c7a5b40d687fddaae103d427
      - Jwt__Issuer=TestAssigment_HK
      - Jwt__Audience=TestAssigment_HK
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:80"

volumes:
  pgdata:
